  ALTER TABLE "SC_ACCOUNT" ADD CONSTRAINT "FK_USERNAME" FOREIGN KEY ("USERNAME")
	  REFERENCES "SC_USERS" ("USERNAME") ENABLE;
      
  ALTER TABLE "SC_HOLDING" ADD CONSTRAINT "FK_ACCTNUM" FOREIGN KEY ("ACCOUNT_NUMBER")
	  REFERENCES "SC_ACCOUNT" ("ACCTNUM") ENABLE;
      
      
  ALTER TABLE "SC_HOLDING" ADD CONSTRAINT "FK_HSNO" FOREIGN KEY ("S_ID")
	  REFERENCES "SC_STOCK_SECURITIES" ("S_ID") ENABLE;
      
  ALTER TABLE "SC_TRADE" ADD CONSTRAINT "FK_TSNO" FOREIGN KEY ("S_ID")
	  REFERENCES "SC_STOCK_SECURITIES" ("S_ID") ENABLE;